config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'cars#index'

  resources :cars, only: [:index, :new, :create] do
    get :import_preview, on: :member
    get :import, on: :member
    delete :cancel_import, on: :member

    collection do
      get :new_import
      post :save_csv
      delete :delete_all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  
  validates :manufacturer, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates_inclusion_of :used, in: [true, false], message: "Must be a boolean value 'true' or 'false'"

end

app/models/import_record.rb
class ImportRecord < ApplicationRecord
  mount_uploader :file, CarUploader

  validates :file, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def new_import
    @upload_csv_form = UploadCsvFrom.new
  end

  def save_csv
    @upload_csv_form = UploadCsvFrom.new(car_params)

    if @upload_csv_form.save
      redirect_to import_preview_car_path(@upload_csv_form.import_record)
    else
      render :new_import
    end
  end

  def cancel_import
    ImportRecord.find(params[:id]).destroy
    flash[:notice] = "Import was canceled."
    redirect_to root_path
  end

  def import_preview
    @presenter = ImportPreviewPresenter.new(import_record_id: params[:id])
    @presenter.validate_rows
  end

  def import
    CarImport::Worker.call!(params[:id])
    flash[:notice] = "Import was successfull!"
    redirect_to root_path
  end

  def delete_all
    # NOTE: Might be worth to create a repository.
    Car.delete_all
    ImportRecord.delete_all

    flash[:notice] = "You have removed all cars!"
    redirect_to root_path
  end

  private

    def car_params
      params.fetch(:upload_csv_from, {}).permit(:file)
    end

end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController

  def new

  end

  def create

  end

  def preview

  end

  def import

  end

  private

    def import_params

    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def add_error_class(key, object)
    return "has-error" if object.errors.messages[key].present?
  end

  def map_flash_keys(key)
    case key
    when "notice"
      "alert-success"
    when "error"
      "alert-danger"
    else
      "alert-warning"
    end
  end

end

app/views/cars/_list.html.haml
%table.table.table-striped
  %thead
    %tr
      %th.text-center
        ID
      %th.text-center
        Manufacturer
      %th.text-center
        Price
      %th.text-center
        Used
      %th.text-center
        Note
  %tbody
    - cars.each do |car|
      %tr.text-center
        %td
          = car.id
        %td
          = car.manufacturer
        %td
          = car.price
        %td
          = car.used
        %td
          = car.note

app/views/cars/import_preview.html.haml
.page-header
  %h1
    Import Preview
    %small.pull-right
      = link_to "Cancel", cancel_import_car_path(@presenter.import_record_id), class: "btn btn-xs btn-primary", method: :delete
      = link_to "Import valid rows", import_car_path(@presenter.import_record_id), class: "btn btn-xs btn-primary"

%table.table
  %thead
    %tr
      %th.text-center
        Total Count
      %th.text-center
        Valid Count
      %th.text-center
        Invalid Count
  %tbody
    %tr.text-center
      %td
        %span.label.label-info
          = @presenter.total_count
      %td
        %span.label.label-success
          = @presenter.valid_count
      %td
        %span.label.label-danger
          = @presenter.invalid_count

- if @presenter.invalid_rows.any?
  %h2
    Invalid rows
  %table.table
    %thead
      %tr
        %th.text-center
          Line
        - @presenter.columns.each do |column|
          %th.text-center
            = column
    %tbody
      - @presenter.invalid_rows.each do |row|
        %tr.text-center
          %td
            = row.line
          - @presenter.columns.each do |column|
            %td
              = row.messages[column.to_sym].to_sentence

- if @presenter.valid_rows.any?
  %h2
    Valid rows
  = render partial: "cars/list", locals: { cars: @presenter.valid_rows }

app/views/cars/index.html.haml
.page-header
  %h1
    Car List
    %small
      = link_to "Delete All", delete_all_cars_path, class: "btn btn-xs btn-danger", data: { confirm: "Are you sure?" }, method: :delete
      = link_to "Import CSV", new_import_cars_path, class: "btn btn-xs btn-primary"

= render partial: "cars/list", locals: { cars: @cars }

app/views/cars/new_import.html.haml
.page-header
  %h1
    Upload CSV File
    %small
      = link_to "Cancel", root_path, class: "btn btn-xs btn-primary"

= form_for @upload_csv_form, url: save_csv_cars_path, class: "form-inline" do |f|
  .form-group{class: add_error_class(:file, @upload_csv_form)}
    = f.label "File input", class: 'control-label'
    = f.file_field :file, class: "form-control filestyle"
    = render partial: "shared/error_messages", locals: {errors: @upload_csv_form.errors, key: :file}
  = f.submit "Upload", class: "btn btn-primary btn-sm"

app/views/layouts/_flash_messages.html.haml
- if flash.any?
  - flash.each do |key, value|
    -# - binding.pry
    #flash-message{class: "alert #{map_flash_keys(key)}"}
      = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CarImporter
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = render partial: "layouts/flash_messages"
      = yield

app/views/shared/_error_messages.html.haml
%ul.error-list
  - errors.messages[key].each do |message|
    %li
      = message